<a href="https://colab.research.google.com/github/Cerino-rigo/EC3002C.602-2023/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

**Importar librería Numpy**

In [2]:
#Importar librería Numpy
import numpy as np

In [3]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)


[1 2 3]


In [4]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)


[[1 2 3]
 [4 5 6]]


In [8]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Un array, es un tipo de dato estructurado que permite almacenar un conjunto de datos homogeneo, es decir, todos ellos del mismo tipo y relacionados. Cada uno de los elementos que componen un array pueden ser de tipo simple como caracteres, entero o real, o de tipo compuesto o estructurado como son vectores, estructuras, listas.

Están organizados en forma de tabla o cuadrícula de distintas dimensiones (1,2,3), también conocida como ejes. La estructura más básica es un vector (1 dimensión)

A los datos almacenados en un array se les denomina elementos; al número de elementos de un array se les denomina tamaño o rango del vector.






**Importar un ndarray utilizando una lista**

In [9]:
lista_2d=[[2,3,9],
          [6,9,2],
          [9,3,7],
          [1,4,8]]

In [12]:
arr = np.array(lista_2d)

**Utilizar la propiedad shape para obtener la forma del arreglo**

In [13]:
arr.shape
# Devuelve la forma del arregalo (Filas x Columnas)

(4, 3)

**Utilizar la propiedad ndim para obtener las dimensiones del arreglo**

In [14]:
arr.ndim


2

**Utilizar la propiedad dtype para conecer el tipo de datos del arreglo**

In [23]:
arr.dtype

dtype('int64')

**Utilizar la propiedad size para conecer la cantidad total de datos del arreglo**

In [24]:
arr.size


12

## Crear arreglos de ceros y unos

**Utilizar la función np.zeros para crear un ndarray con la forma 4x3**

In [27]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Utilizar la función np.ones para crear un ndarray con la forma 5x5**

In [28]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Crear un ndarray de 1 dimensión con valores del 0 al 49 (Ej. [1,2,3,...])**

In [31]:
np.arange(50)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Crear un ndarray de 2 dimensión con la forma 2x50,los valores deben ser del 0 al 49 (Ej. [[0,1,2,3,4],[5,6,..]])

In [32]:
np.arange(50).reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr2 = np.arange(50)
arr3 = arr2.reshape(2,25)
print(arr3)


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]


## Crear secuancias con Numpy

**Utilizar np.arange para crear un ndarray con los valores del 20 al 100, deben ir de 2 en 2 (Ej. [20,22,..])**

In [45]:
np.arange(20, 100, 2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

**arange(start, stop, step)** Los valores se generan dentro del intervalo semiabierto [start, stop), con un espaciado entre valores dado por step.

**Utilizar np.linspace para crear un ndarray con valores entre el 25 y 95**

In [50]:
np.linspace(25, 95, 30)

array([25.        , 27.4137931 , 29.82758621, 32.24137931, 34.65517241,
       37.06896552, 39.48275862, 41.89655172, 44.31034483, 46.72413793,
       49.13793103, 51.55172414, 53.96551724, 56.37931034, 58.79310345,
       61.20689655, 63.62068966, 66.03448276, 68.44827586, 70.86206897,
       73.27586207, 75.68965517, 78.10344828, 80.51724138, 82.93103448,
       85.34482759, 87.75862069, 90.17241379, 92.5862069 , 95.        ])

**numpy.linspace(start, stop, num=50)**

Devuelve números espaciados uniformemente sobre un intervalo especificado.

Devuelve ***num*** de muestras espaciadas uniformemente, calculadas sobre el intervalo [start, stop].

El punto final del intervalo puede excluirse opcionalmente.

## Operaciones con arreglos

In [52]:
a = np.linspace(23, 45, 6)
b = np.linspace(30, 40, 6)
print(a,b)

[23.  27.4 31.8 36.2 40.6 45. ] [30. 32. 34. 36. 38. 40.]


**Sumar los arreglos a + b**

In [56]:
a + b


array([53. , 59.4, 65.8, 72.2, 78.6, 85. ])

**Unir los arreglos anteriores y guardalos en una nueva variable**

In [60]:
c = np.concatenate((a,b))
c

array([23. , 27.4, 31.8, 36.2, 40.6, 45. , 30. , 32. , 34. , 36. , 38. ,
       40. ])

**Ordenar los valores del arreglo "c"**

In [61]:
c.sort()
c

array([23. , 27.4, 30. , 31.8, 32. , 34. , 36. , 36.2, 38. , 40. , 40.6,
       45. ])

In [ ]:
## Estadística con Numpy

In [103]:
estadisticos = np.random.randint(100,size=(300))
estadisticos

array([84, 97,  9, 74, 80, 62, 16, 45, 32, 64, 41, 26, 82, 66, 37, 64, 47,
       20, 59, 26, 18, 12, 30, 40, 75, 49, 33,  6,  2, 85, 66, 53, 11, 50,
        8, 30, 66, 33, 81, 39, 89, 56, 34, 29, 57, 49, 57,  5, 52, 30, 46,
       52, 55, 81, 55, 23, 61, 63, 47, 18, 26, 89, 30,  2, 50, 99, 84, 78,
       83, 88,  0, 46, 82, 46, 51, 67, 53, 75, 43, 82, 30,  5, 95, 36, 45,
       29, 68, 85, 61, 44, 88, 37, 36, 94, 63, 67, 48, 80, 88, 17, 79, 74,
       46, 58, 32, 13, 73, 49, 90, 39, 42, 91, 47, 87, 91, 38,  5, 59, 38,
       90,  7, 34, 34, 63, 44, 22, 34, 22,  9, 21, 72, 87, 30, 94, 68, 65,
       27, 28,  5, 47,  2, 52, 13, 47, 43, 26, 18, 56, 51, 79, 85, 51, 46,
       14, 47, 43, 35, 52, 75,  5, 51, 89, 30, 54, 53, 55, 11, 27, 49, 73,
       79, 88, 77, 29, 79, 97, 18,  8, 98, 57, 76, 21, 48, 88, 11, 46,  6,
       35, 48, 72, 23, 83, 39, 11, 29, 25, 51, 97, 47,  2, 97,  9, 84, 58,
       13, 40,  4,  0, 66, 98, 16,  8, 29, 10, 25, 64,  7, 38, 85, 40,  5,
       70, 37, 44, 52, 76

**random.randint(low, high=None, size=None, dtype=int)**

Devuelve enteros aleatorios desde ***low*** (incluido) hasta ***high*** (excluido).


**Tomar un sub arreglo del original**

In [104]:
estadisticos1 = estadisticos[40:80]
estadisticos1

array([89, 56, 34, 29, 57, 49, 57,  5, 52, 30, 46, 52, 55, 81, 55, 23, 61,
       63, 47, 18, 26, 89, 30,  2, 50, 99, 84, 78, 83, 88,  0, 46, 82, 46,
       51, 67, 53, 75, 43, 82])

**Utilizar la función max() y min() para obtener el valor máximo y mínimo y promedio del arrego "estadisticos1"**

In [105]:
estadisticos1.min()


0

In [106]:
estadisticos1.max()

99

**Utilizar la función mean() y std() para obtener el promedio y la desviación estandar del arrego "estadisticos1"**


In [107]:
estadisticos1.mean()

53.325

In [108]:
estadisticos1.std()

24.82477341286321

**Utilizar la función sum() para obtener la suma total de los elementos del arrego "estadisticos1"**


In [109]:
estadisticos1.sum()

2133

##Estadísticas en 2D

In [114]:
estadistica_2D = np.random.randint(50, size=(6, 8))
estadistica_2D

array([[22, 48, 43,  8, 27,  1, 10, 22],
       [25, 36, 29, 29, 34, 34, 36, 41],
       [46, 37, 22, 17, 48,  4, 17,  3],
       [ 7, 15, 44, 14,  8, 38, 25,  8],
       [ 1, 41, 32, 42, 33, 23, 23, 46],
       [29, 19, 47, 32, 10,  6, 23,  7]])

**Utilizar la función min() para obtener el valor mínimo de cada columna y fila en el ndarray "estadistica_2D"**

In [115]:
estadistica_2D.min(axis=0)

array([ 1, 15, 22,  8,  8,  1, 10,  3])

In [116]:
estadistica_2D.min(axis=1)

array([ 1, 25,  3,  7,  1,  6])

**numpy.min(a, axis=None)**
***axis*** = Eje o ejes a lo largo de los cuales operar (0 = columnas, 1 = filas).

## Filtros

**Obtener los valores mayores a 8 en el arreglo "estadistica_2d"**

In [119]:
estadistica_2D > 8

array([[ True,  True,  True, False,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False],
       [False,  True,  True,  True, False,  True,  True, False],
       [False,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False]])

In [120]:
estadistica_2D[estadistica_2D > 8]

array([22, 48, 43, 27, 10, 22, 25, 36, 29, 29, 34, 34, 36, 41, 46, 37, 22,
       17, 48, 17, 15, 44, 14, 38, 25, 41, 32, 42, 33, 23, 23, 46, 29, 19,
       47, 32, 10, 23])

## Acceder a elementos del arreglo

Seleccionar el tercer valor de la cuarta fila de "arr_2D"

In [121]:
arr_2D = np.random.randint(50, size=(12, 10))
arr_2D

array([[ 5, 19,  1,  6, 39, 36, 13, 28,  2,  0],
       [27, 27,  2,  8, 45, 19, 31, 16, 32, 13],
       [ 3, 19, 47, 30, 30, 28, 14,  5,  1,  6],
       [ 0,  9, 27, 31,  4, 22, 21, 14, 41, 19],
       [41, 36, 49, 16, 11,  0, 49, 26, 16, 29],
       [15,  4, 41,  5,  6, 10, 49, 28,  3, 15],
       [ 2, 33, 28, 36, 46, 21, 11, 21,  6, 24],
       [37,  2,  3, 10,  5, 29, 23,  5, 20, 29],
       [ 9, 40, 37, 33, 32, 47, 21,  5, 24, 35],
       [27, 22, 32, 14, 10, 19, 35, 18, 47,  0],
       [31, 44,  1, 10,  0, 38, 18, 34, 37,  2],
       [ 5, 43,  9, 32, 10, 19, 44, 43, 39, 12]])

In [124]:
arr_2D[3,2]

27

Seleccionar los valores en la posición 5 de las filas 5-8





In [126]:
arr_2D[5:8,5]

array([10, 21, 29])

Seleccionar los valores en la posición 3-6 de las filas 1-4

In [127]:
arr_2D[1:4,3:6]

array([[ 8, 45, 19],
       [30, 30, 28],
       [31,  4, 22]])